# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='circles',
            fields=[
                ('DISTNAM', models.CharField(max_length=50)),
                ('DIST', models.CharField(max_length=4)),
                ('CIRCLE', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('CIRCLENAM', models.CharField(max_length=50)),
                ('RANGE', models.CharField(max_length=4)),
                ('RANGENAM', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='roads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RNG', models.CharField(max_length=5)),
                ('DIST', models.CharField(max_length=5)),
                ('ROADNAME', models.CharField(max_length=50)),
                ('ROAD', models.IntegerField()),
                ('PS', models.CharField(max_length=5)),
                ('PLACE_OCC', models.CharField(max_length=50)),
                ('NEW', models.CharField(max_length=50)),
                ('PSNAME', models.CharField(max_length=50)),
                ('NEW1', models.CharField(max_length=50)),
                ('CIRCLE', models.ManyToManyField(to='fir.circles')),
            ],
        ),
        migrations.AlterField(
            model_name='details',
            name='CIRCLE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.circles'),
        ),
        migrations.AlterField(
            model_name='details',
            name='DIST',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='details',
            name='PS',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='details',
            name='RNG',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='details',
            name='ROAD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.roads'),
        ),
    ]
