# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0002_auto_20170613_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='sections',
            fields=[
                ('SECTION', models.IntegerField(primary_key=True, serialize=False)),
                ('SECTIONDTL', models.CharField(max_length=50)),
                ('ACCTYPE', models.CharField(max_length=5)),
                ('ACCTYPEN', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='roads',
            name='id',
        ),
        migrations.AlterField(
            model_name='details',
            name='SECTION',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.sections'),
        ),
        migrations.AlterField(
            model_name='roads',
            name='NEW',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
