# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0003_auto_20170614_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roads',
            name='NEW1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='roads',
            name='PSNAME',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
