# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 19:10
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0006_auto_20170614_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='ROAD',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='CIRCLE', chained_model_field='CIRCLE', on_delete=django.db.models.deletion.CASCADE, to='fir.roads'),
        ),
    ]
