# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0007_auto_20170615_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='policestation',
            fields=[
                ('DISTNAM', models.CharField(max_length=50)),
                ('DIST', models.CharField(max_length=20)),
                ('CIRCLENAM', models.CharField(max_length=50)),
                ('RANGE', models.CharField(max_length=4)),
                ('RANGENAM', models.CharField(max_length=50)),
                ('PS', models.CharField(max_length=20)),
                ('PSNAME', models.CharField(max_length=100)),
                ('CIRCLE_PS', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('CIRCLE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.circles')),
            ],
        ),
        migrations.AlterField(
            model_name='details',
            name='PS',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='CIRCLE', chained_model_field='CIRCLE', on_delete=django.db.models.deletion.CASCADE, to='fir.policestation'),
        ),
    ]
