# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0008_auto_20170615_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='injured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PS', models.CharField(max_length=5)),
                ('FIRNO', models.IntegerField()),
                ('YEAR', models.PositiveIntegerField()),
                ('INJSEX', models.CharField(max_length=15)),
                ('INJAGE', models.PositiveIntegerField()),
                ('INJTYPE', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='killed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PS', models.CharField(max_length=5)),
                ('FIRNO', models.IntegerField()),
                ('YEAR', models.PositiveIntegerField()),
                ('SEX', models.CharField(max_length=15)),
                ('AGE', models.PositiveIntegerField()),
                ('TYPE', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='details',
            name='ACCAGE',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='details',
            name='dri_age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name='killed',
            name='ACCID_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.details'),
        ),
        migrations.AddField(
            model_name='injured',
            name='ACCID_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.details'),
        ),
    ]
