# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0009_auto_20170616_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='ACCAGE',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='ACCSEX',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='TIME_TYPE',
            field=models.CharField(choices=[('IN FIR', 'IN FIR'), ('APPROX.', 'APPROX.')], max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='dri_sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=15),
        ),
        migrations.AlterField(
            model_name='injured',
            name='INJAGE',
            field=models.CharField(choices=[('<10', '<10'), ('11-18', '11-18'), ('19-30', '19-30'), ('31-40', '31-40'), ('>40', '>40')], max_length=15),
        ),
        migrations.AlterField(
            model_name='injured',
            name='INJSEX',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=15),
        ),
        migrations.AlterField(
            model_name='injured',
            name='INJTYPE',
            field=models.CharField(choices=[('SCL', 'School Children'), ('PPL', 'Police Person'), ('OTH', 'Other')], max_length=5),
        ),
        migrations.AlterField(
            model_name='killed',
            name='AGE',
            field=models.CharField(choices=[('<10', '<10'), ('11-18', '11-18'), ('19-30', '19-30'), ('31-40', '31-40'), ('>40', '>40')], max_length=15),
        ),
        migrations.AlterField(
            model_name='killed',
            name='SEX',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=15),
        ),
        migrations.AlterField(
            model_name='killed',
            name='TYPE',
            field=models.CharField(choices=[('SCL', 'School Children'), ('PPL', 'Police Person'), ('OTH', 'Other')], max_length=20),
        ),
    ]
