# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0011_auto_20170618_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehtype1',
            old_name='SRK',
            new_name='TSRI',
        ),
        migrations.RenameField(
            model_name='vehtype1',
            old_name='TSRIT',
            new_name='TSRK',
        ),
        migrations.RemoveField(
            model_name='vehtype1',
            name='id',
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='VEHTYPE',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
