# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0017_auto_20170618_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehtype1',
            name='VEHTYPE',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
