# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0022_auto_20170618_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehtype1',
            name='NONINJ',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='SIMPLE',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
