# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0023_auto_20170618_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehtype1',
            name='AMBI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='AMBK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='ANII',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='ANIK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='BLBI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='BLBK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='BULI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='BULK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='BUSI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='BUSK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='CARI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='CARK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='CRNI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='CRNK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='CYCI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='CYCK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='CYRI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='CYRK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='DLVI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='DLVK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='DTCI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='DTCK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='ELTI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='ELTK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='FATAL',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='HDCI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='HDCK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='HTVI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='HTVK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='MATI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='MATK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='MBSI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='MBSK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='MILI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='MILK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='NONINJ',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='OSBI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='OSBK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='PASI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='PASK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='PEDESTRIAN',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='PEDI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='PEDK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='PERINJ',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='PERKIL',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='POVI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='POVK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='SLFI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='SLFK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='STRI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='STRK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='TAXI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='TAXK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='TMPI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='TMPK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='TNGI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='TNGK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='TNKI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='TNKK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='TRCI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='TRCK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='TSRI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='TSRK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='TWWI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='TWWK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='UDTI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='UDTK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='UNKI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='UNKK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='WLLI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehtype1',
            name='WLLK',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
