# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0025_vehtype2'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehtype2',
            name='CYCK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vehtype2',
            name='MATI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vehtype2',
            name='MATK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vehtype2',
            name='TNGI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vehtype2',
            name='TNGK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vehtype2',
            name='TNKI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vehtype2',
            name='TNKK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vehtype2',
            name='UNKI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vehtype2',
            name='UNKK',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='VEHTYPE2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.vehtype2'),
        ),
    ]
