# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0026_auto_20170618_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehtype2',
            name='VEHTYPE',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
