# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0030_auto_20170620_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('SNO', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('TYPE', models.CharField(max_length=150)),
                ('CATEGORY', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='details',
            name='LOCATION',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.location'),
        ),
        migrations.AlterField(
            model_name='details',
            name='dri_age',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='dri_fath',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='details',
            name='dri_lic_date_issu',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='dri_lic_date_upto',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='dri_lic_no',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='details',
            name='dri_lic_status',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='dri_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='details',
            name='dri_place',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
