# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0031_auto_20170620_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='accid_type',
            fields=[
                ('SNO', models.PositiveIntegerField(max_length=20, primary_key=True, serialize=False)),
                ('TYPE', models.CharField(max_length=200)),
                ('CATEGORY', models.CharField(max_length=100)),
                ('CODE', models.CharField(max_length=20)),
                ('VICTIM', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='details',
            name='ACCID_TYPE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.accid_type'),
        ),
    ]
