# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0032_auto_20170620_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accid_type',
            name='SNO',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
