# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0033_auto_20170620_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accid_type',
            name='CODE',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
