# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0034_auto_20170620_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='SELF_TYPE',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='self_type',
            name='CODE',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='self_type',
            name='SNO',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
