# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0037_auto_20170620_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='BLACK_SPOT',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='BLACK_SPOT_NO',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='BRIEF_FACTS',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='details',
            name='BUS_NO',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='CN_DT',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='details',
            name='CONFIRM',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='CONVERT',
            field=models.CharField(blank=True, choices=[('T', 'TRUE'), ('F', 'FALSE')], max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='CONVERT_DATE',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='CONVERT_FN',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='details',
            name='FOR_BLK',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='F_STATUS',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='HIT_AND_RUN_UPDATE1',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='PILLION_HELMET',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='REMARK',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='details',
            name='RIDER_HELMET',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='RNOV1A',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='RNOV1B',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='details',
            name='RNOV2A',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='details',
            name='RNOV2B',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='details',
            name='SCANNED',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='STATE',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='STATUS',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='TWW1',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='TWW2',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='case_status',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='convert_case',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='dri_add1',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='routeno',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
