# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0038_auto_20170620_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='SELF_TYPE',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fir.self_type'),
        ),
        migrations.AlterField(
            model_name='details',
            name='dri_add',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='details',
            name='dri_arrest',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='dri_sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=15),
        ),
    ]
