# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0039_auto_20170620_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='INJURED',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='TIME_OCC',
            field=models.CharField(max_length=15),
        ),
    ]
