# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0041_auto_20170620_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='ACCAGE',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='ACCSEX',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='DATE_OCC',
            field=models.DateField(verbose_name='date occ'),
        ),
        migrations.AlterField(
            model_name='details',
            name='Intersection',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
