# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0042_auto_20170620_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='CONVERT_DATE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='DATE_OCC',
            field=models.DateField(verbose_name='DATE_OCC'),
        ),
        migrations.AlterField(
            model_name='details',
            name='dri_lic_date_issu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='dri_lic_date_upto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
