# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0043_auto_20170620_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='dri_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
