# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-22 09:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0045_auto_20170622_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accid_type',
            name='TYPE',
            field=models.CharField(default='ON ROAD', max_length=200),
        ),
        migrations.AlterField(
            model_name='details',
            name='FIRNO',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='details',
            name='RNOV1A',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='details',
            name='RNOV1B',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='details',
            name='RNOV2A',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='details',
            name='dri_age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)]),
        ),
    ]
