# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-22 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0046_auto_20170622_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accid_type',
            name='TYPE',
            field=models.CharField(max_length=200),
        ),
    ]
