# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0048_auto_20170622_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='LONGITUDE',
            field=models.CharField(max_length=15),
        ),
    ]
