# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 07:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0050_auto_20170623_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='ACCAGE',
            field=models.CharField(blank=True, default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='ACCID_TYPE',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fir.accid_type'),
        ),
        migrations.AlterField(
            model_name='details',
            name='ACCSEX',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='ACCTYPE',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='details',
            name='BLACK_SPOT',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='BLACK_SPOT_NO',
            field=models.CharField(blank=True, default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='BRIEF_FACTS',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='details',
            name='BUS_NO',
            field=models.CharField(blank=True, default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='CATEGORY',
            field=models.CharField(blank=True, default=0, max_length=140),
        ),
        migrations.AlterField(
            model_name='details',
            name='CN_DT',
            field=models.CharField(blank=True, default=0, max_length=150),
        ),
        migrations.AlterField(
            model_name='details',
            name='CONFIRM',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='CONVERT',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='No', max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='CONVERT_DATE',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='CONVERT_FN',
            field=models.CharField(blank=True, default=0, max_length=150),
        ),
        migrations.AlterField(
            model_name='details',
            name='DUPL',
            field=models.CharField(blank=True, default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='FOR_BLK',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='F_STATUS',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='HIT_AND_RUN_UPDATE1',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='INJBOY',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='details',
            name='INJFEMALE',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='details',
            name='INJGIRL',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='details',
            name='INJMALE',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='details',
            name='INJURED',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='details',
            name='Intersection',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='details',
            name='KILBOY',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='details',
            name='KILFEMALE',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='details',
            name='KILGIRL',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='details',
            name='KILLED',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='details',
            name='KILMALE',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='details',
            name='LATITUDE',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='LOCATION',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='fir.location'),
        ),
        migrations.AlterField(
            model_name='details',
            name='LONGITUDE',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='PEDESTRIAN',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='details',
            name='PENDING',
            field=models.CharField(blank=True, default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='PILLION_HELMET',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='PLACE_OCC',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='details',
            name='REMARK',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='details',
            name='RIDER_HELMET',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='RNOV1A',
            field=models.CharField(blank=True, default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='details',
            name='RNOV1B',
            field=models.CharField(blank=True, default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='details',
            name='RNOV2A',
            field=models.CharField(blank=True, default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='details',
            name='RNOV2B',
            field=models.CharField(blank=True, default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='details',
            name='SCANNED',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='SELF_TYPE',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='fir.self_type'),
        ),
        migrations.AlterField(
            model_name='details',
            name='STATE',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='STATUS',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='TIME_OCC',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='details',
            name='TWW1',
            field=models.CharField(blank=True, default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='TWW2',
            field=models.CharField(blank=True, default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='VICTIM',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='details',
            name='case_status',
            field=models.CharField(blank=True, choices=[('NO INFORMATION', 'NO INFORMATION'), ('PENDING INVESTIGATION', 'PENDING INVESTIGATION'), ('PENDING TRIAL', 'PENDING TRIAL'), ('CONVICTED', 'CONVICTED'), ('ACQUITTED', 'ACQUITTED'), ('CANCELLED', 'CANCELLED')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='convert_case',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='dri_add',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='details',
            name='dri_add1',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='dri_age',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='details',
            name='dri_arrest',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='dri_fath',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='details',
            name='dri_lic_date_issu',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='dri_lic_date_upto',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='dri_lic_no',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='details',
            name='dri_lic_status',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='dri_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='details',
            name='dri_place',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='details',
            name='dri_sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='routeno',
            field=models.CharField(blank=True, default=0, max_length=15),
        ),
    ]
