# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-26 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0053_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='circle',
            field=models.CharField(default='no', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='designation',
            field=models.CharField(default='INs', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='district_circle',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='emp_id',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='range_circle',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
