# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-26 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0054_auto_20170626_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.circles'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='designation',
            field=models.CharField(choices=[('DCP', 'DCP'), ('ACP', 'ACP'), ('INSPECTOR', 'INSPECTOR'), ('ACCIDENT RESEARCH CELL', 'ACCIDENT RESEARCH CELL')], max_length=30),
        ),
    ]
