# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-26 16:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fir', '0056_auto_20170626_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', max_length=50)),
                ('emp_id', models.CharField(default='0', max_length=15)),
                ('district_circle', models.CharField(blank=True, max_length=30)),
                ('range_circle', models.CharField(blank=True, max_length=30)),
                ('designation', models.CharField(choices=[('DCP', 'DCP'), ('ACP', 'ACP'), ('INSPECTOR', 'INSPECTOR'), ('ACCIDENT RESEARCH CELL', 'ACCIDENT RESEARCH CELL')], max_length=30)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.circles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='circle',
        ),
        migrations.DeleteModel(
            name='userprofile',
        ),
    ]
