# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0058_auto_20170626_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='ACC_PHOTO',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='details',
            name='FIR_PHOTO',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
