# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0062_auto_20170627_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='area_type',
            fields=[
                ('Atype_Code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Area_Type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='driver_fault',
            fields=[
                ('DF_Code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('DF_Details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='edu_qual',
            fields=[
                ('EDQF_Code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('EDQF_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='remedies',
            fields=[
                ('Rem_Code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Rem_Description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='road_character',
            fields=[
                ('RC_Code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('RC_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='road_condition',
            fields=[
                ('RCN_Code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('RCN_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='road_engg_fault',
            fields=[
                ('RENF_Code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('RENF_Details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='road_env_fault',
            fields=[
                ('REF_Code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('REF_Details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='road_level',
            fields=[
                ('RL_Code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('RL_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='seperation',
            fields=[
                ('S_Code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('S_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='study_parameter',
            fields=[
                ('SPM_Code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('SPM_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='surface_condition',
            fields=[
                ('SC_Code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('SC_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='surface_type',
            fields=[
                ('SFT_Code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('SFT_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='veh_mech_fault',
            fields=[
                ('VMF_Code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('VMF_Details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle_loaded_condition',
            fields=[
                ('VLC_Code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('VLC_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='victim_fault',
            fields=[
                ('VF_Code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('VF_Details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='victim_person_status',
            fields=[
                ('Victim_Person_Status', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='weather_cond',
            fields=[
                ('WC_Code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('WC_Details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='work_status',
            fields=[
                ('WS_Code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('WS_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='details',
            name='ACC_PHOTO',
            field=models.FileField(blank=True, default='', upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='details',
            name='FIR_PHOTO',
            field=models.FileField(blank=True, default='', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='details',
            name='AREA_TYPE',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.area_type'),
        ),
        migrations.AddField(
            model_name='details',
            name='DRIVER_FAULT',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.driver_fault'),
        ),
        migrations.AddField(
            model_name='details',
            name='EDU_QUAL',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.edu_qual'),
        ),
        migrations.AddField(
            model_name='details',
            name='REMEDIES',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.remedies'),
        ),
        migrations.AddField(
            model_name='details',
            name='ROAD_CHARACTER',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.road_character'),
        ),
        migrations.AddField(
            model_name='details',
            name='ROAD_CONDITION',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.road_condition'),
        ),
        migrations.AddField(
            model_name='details',
            name='ROAD_ENGG_FAULT',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.road_engg_fault'),
        ),
        migrations.AddField(
            model_name='details',
            name='ROAD_ENV_FAULT',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.road_env_fault'),
        ),
        migrations.AddField(
            model_name='details',
            name='ROAD_LEVEL',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.road_level'),
        ),
        migrations.AddField(
            model_name='details',
            name='SEPERATION',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.seperation'),
        ),
        migrations.AddField(
            model_name='details',
            name='STUDY_PARAMETER',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.study_parameter'),
        ),
        migrations.AddField(
            model_name='details',
            name='SURFACE_CONDITION',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.surface_condition'),
        ),
        migrations.AddField(
            model_name='details',
            name='SURFACE_TYPE',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.surface_type'),
        ),
        migrations.AddField(
            model_name='details',
            name='VEHICLE_LOADED_CONDITION',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.vehicle_loaded_condition'),
        ),
        migrations.AddField(
            model_name='details',
            name='VEH_MECH_FAULT',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.veh_mech_fault'),
        ),
        migrations.AddField(
            model_name='details',
            name='VICTIM_FAULT',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.victim_fault'),
        ),
        migrations.AddField(
            model_name='details',
            name='VICTIM_PERSON_STATUS',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.victim_person_status'),
        ),
        migrations.AddField(
            model_name='details',
            name='WEATHER_COND',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.weather_cond'),
        ),
        migrations.AddField(
            model_name='details',
            name='WORK_STATUS',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.work_status'),
        ),
    ]
