# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0063_auto_20170627_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.circles'),
        ),
    ]
