# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0064_auto_20170628_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='designation',
            field=models.CharField(choices=[('', '-----------'), ('DCP', 'DCP'), ('ACP', 'ACP'), ('INSPECTOR', 'INSPECTOR'), ('ACCIDENT RESEARCH CELL', 'ACCIDENT RESEARCH CELL')], max_length=30),
        ),
    ]
