# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0067_auto_20170629_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junction_control',
            name='GL_JCTRL_Code',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
