# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 07:27
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0068_auto_20170629_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='collision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VIC_TYPE', models.CharField(max_length=15)),
                ('COL_TYPE', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='offender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUBVEHICLE_TYPE1', models.CharField(blank=True, default=0, max_length=15)),
                ('routeno1', models.CharField(blank=True, default=0, max_length=15)),
                ('rcno1', models.CharField(blank=True, default=0, max_length=15)),
                ('dri_name', models.CharField(blank=True, default='', max_length=150)),
                ('dri_rel_name', models.CharField(blank=True, default='', max_length=150)),
                ('dri_sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=15)),
                ('dri_age', models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)])),
                ('dri_add', models.CharField(blank=True, default='', max_length=150)),
                ('OTHER_EDU_QUAL', models.CharField(blank=True, default='', max_length=50)),
                ('OTHER_WORK_STATUS', models.CharField(blank=True, default='', max_length=50)),
                ('DRI_DRUNK', models.BooleanField()),
                ('dri_lic_no', models.CharField(blank=True, default='', max_length=150)),
                ('dri_lic_from', models.CharField(blank=True, default='', max_length=150)),
                ('dri_lic_date_issu', models.DateField(null=True)),
                ('dri_lic_date_upto', models.DateField(null=True)),
                ('RNOV1A', models.CharField(blank=True, default=0, max_length=4)),
                ('RNOV1B', models.CharField(blank=True, default=0, max_length=4)),
                ('dri_lic_status', models.CharField(blank=True, default='', max_length=15)),
                ('EDU_QUAL', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.edu_qual')),
                ('STUDY_PARAMETER1', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.study_parameter')),
                ('VEHICLE_LOADED_CONDITION1', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.vehicle_loaded_condition')),
                ('VEHTYPE1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.vehtype1')),
                ('WORK_STATUS', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.work_status')),
            ],
        ),
        migrations.CreateModel(
            name='victim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VIC_TYPE', models.CharField(choices=[('SCL', 'School Children'), ('PPL', 'Police Person'), ('OTH', 'Other')], max_length=15)),
                ('VICSEX', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=15)),
                ('VICAGE', models.CharField(choices=[('<10', '<10'), ('11-18', '11-18'), ('19-30', '19-30'), ('31-40', '31-40'), ('>40', '>40')], max_length=15)),
                ('VICTYPE', models.CharField(choices=[('SCL', 'School Children'), ('PPL', 'Police Person'), ('OTH', 'Other')], max_length=15)),
                ('VIC_IN_VEH', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
                ('OFFEND', models.CharField(choices=[('OFFENDING', 'Offending'), ('VICTIM VEHICLE', 'Victim Vehicle')], max_length=15)),
                ('VIC_SEAT_BELT', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
                ('VIC_HELMET', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
                ('HELMET_STANDARD', models.CharField(choices=[('STANDARD', 'Standard'), ('SUB STANDARD', 'Sub Standard'), ('NOT KNOWN', 'Not Known')], max_length=15)),
                ('VIC_OTHER_EDU_QUAL', models.CharField(blank=True, default='', max_length=50)),
                ('VIC_OTHER_WORK_STATUS', models.CharField(blank=True, default='', max_length=50)),
                ('VIC_DRI_DRUNK', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='victim_vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUBVEHICLE_TYPE2', models.CharField(blank=True, default=0, max_length=15)),
                ('routeno2', models.CharField(blank=True, default=0, max_length=15)),
                ('rgno2', models.CharField(blank=True, default=0, max_length=15)),
                ('STUDY_PARAMETER2', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.study_parameter')),
                ('VEHICLE_LOADED_CONDITION2', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.vehicle_loaded_condition')),
                ('VEHTYPE2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.vehtype2')),
            ],
        ),
        migrations.RemoveField(
            model_name='details',
            name='ACCDRUNK',
        ),
        migrations.RemoveField(
            model_name='details',
            name='EDU_QUAL',
        ),
        migrations.RemoveField(
            model_name='details',
            name='RNOV1A',
        ),
        migrations.RemoveField(
            model_name='details',
            name='RNOV1B',
        ),
        migrations.RemoveField(
            model_name='details',
            name='RNOV2A',
        ),
        migrations.RemoveField(
            model_name='details',
            name='RNOV2B',
        ),
        migrations.RemoveField(
            model_name='details',
            name='STUDY_PARAMETER',
        ),
        migrations.RemoveField(
            model_name='details',
            name='TIME_TYPE',
        ),
        migrations.RemoveField(
            model_name='details',
            name='TWW1',
        ),
        migrations.RemoveField(
            model_name='details',
            name='TWW2',
        ),
        migrations.RemoveField(
            model_name='details',
            name='VEHICLE_LOADED_CONDITION',
        ),
        migrations.RemoveField(
            model_name='details',
            name='VEHTYPE1',
        ),
        migrations.RemoveField(
            model_name='details',
            name='VEHTYPE2',
        ),
        migrations.RemoveField(
            model_name='details',
            name='WORK_STATUS',
        ),
        migrations.RemoveField(
            model_name='details',
            name='dri_add',
        ),
        migrations.RemoveField(
            model_name='details',
            name='dri_age',
        ),
        migrations.RemoveField(
            model_name='details',
            name='dri_arrest',
        ),
        migrations.RemoveField(
            model_name='details',
            name='dri_fath',
        ),
        migrations.RemoveField(
            model_name='details',
            name='dri_lic_date_issu',
        ),
        migrations.RemoveField(
            model_name='details',
            name='dri_lic_date_upto',
        ),
        migrations.RemoveField(
            model_name='details',
            name='dri_lic_no',
        ),
        migrations.RemoveField(
            model_name='details',
            name='dri_name',
        ),
        migrations.RemoveField(
            model_name='details',
            name='dri_place',
        ),
        migrations.RemoveField(
            model_name='details',
            name='dri_sex',
        ),
        migrations.RemoveField(
            model_name='details',
            name='routeno',
        ),
        migrations.AddField(
            model_name='details',
            name='ACC_SKETCH_PHOTO',
            field=models.FileField(blank=True, default='', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='details',
            name='AREA',
            field=models.CharField(choices=[('URBAN', 'URBAN'), ('RURAL', 'RURAL')], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='AREA_TYPE_OTHER',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='details',
            name='CAUSE',
            field=models.CharField(choices=[('KNOWN', 'Known'), ('UNKNOWN', 'Unknown')], default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='FIR_DATE',
            field=models.DateField(default=datetime.datetime(2017, 7, 4, 12, 57, 18, 369000), verbose_name='FIR DATE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='FLYOVER_UNDERP',
            field=models.CharField(choices=[('Ascending Flyover', 'Ascending Flyover'), ('Descending Flyover', 'Descending Flyover'), ('Ascending Flyover Loop', 'Ascending Flyover Loop'), ('Descending Flyover Loop', 'Desscending Flyover Loop')], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='MINORROADNAME',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='OTHER_DRIVER_FAULT',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='details',
            name='OTHER_FAULT',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='details',
            name='OTHER_ROAD_ENGG_FAULT',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='details',
            name='OTHER_ROAD_ENV_FAULT',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='details',
            name='OTHER_VEC_MEH_FAULT',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='details',
            name='OTHER_VICTIM_FAULT',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='details',
            name='OTHER_WEATHER_COND_FAULT',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='details',
            name='OVER_SPEED_FAULT',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='ROAD_CHARACTER_REMARKS',
            field=models.CharField(blank=True, default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='details',
            name='ROAD_CONDITION_REMARKS',
            field=models.CharField(blank=True, default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='details',
            name='SURFACE_CONDITION_REMARKS',
            field=models.CharField(blank=True, default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='details',
            name='TIME_KNOWN',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='details',
            name='CN_DT',
            field=models.CharField(blank=True, default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='victim',
            name='ACCID_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.details'),
        ),
        migrations.AddField(
            model_name='victim',
            name='VICTYPE1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.victim_person_status1'),
        ),
        migrations.AddField(
            model_name='victim',
            name='VIC_EDU_QUAL',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.edu_qual'),
        ),
        migrations.AddField(
            model_name='victim',
            name='VIC_WORK_STATUS',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.work_status'),
        ),
        migrations.AddField(
            model_name='collision',
            name='ACCID_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.details'),
        ),
    ]
