# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0069_auto_20170704_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='victim_person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INJKIL', models.CharField(choices=[('INJURED', 'Injured'), ('KILLED', 'Killed')], max_length=15)),
                ('VICSEX', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=15)),
                ('VICAGE', models.CharField(choices=[('<10', '<10'), ('11-18', '11-18'), ('19-30', '19-30'), ('31-40', '31-40'), ('>40', '>40')], max_length=15)),
                ('PER_STAT_TYPE', models.CharField(choices=[('SCL', 'School Children'), ('PPL', 'Police Person'), ('OTH', 'Other')], max_length=15)),
                ('VIC_IN_VEH', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
                ('OFFEND', models.CharField(blank=True, choices=[('OFFENDING', 'Offending'), ('VICTIM VEHICLE', 'Victim Vehicle')], default='', max_length=15)),
                ('VEH_INFO', models.CharField(blank=True, max_length=5)),
                ('VIC_SEAT_BELT', models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], default='', max_length=5)),
                ('VIC_HELMET', models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], default='', max_length=5)),
                ('HELMET_STANDARD', models.CharField(blank=True, choices=[('STANDARD', 'Standard'), ('SUB STANDARD', 'Sub Standard'), ('NOT KNOWN', 'Not Known')], default='', max_length=15)),
                ('VIC_OTHER_EDU_QUAL', models.CharField(blank=True, default='', max_length=50)),
                ('VIC_OTHER_WORK_STATUS', models.CharField(blank=True, default='', max_length=50)),
                ('VIC_DRI_DRUNK', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='victim',
            name='ACCID_ID',
        ),
        migrations.RemoveField(
            model_name='victim',
            name='VICTYPE1',
        ),
        migrations.RemoveField(
            model_name='victim',
            name='VIC_EDU_QUAL',
        ),
        migrations.RemoveField(
            model_name='victim',
            name='VIC_WORK_STATUS',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='SOAREA_TYPE',
            new_name='AREA_TYPE2_OTHER',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='SECTION',
            new_name='OF_SECTION',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='OTHER_FAULT',
            new_name='OTHER_REMARK',
        ),
        migrations.RemoveField(
            model_name='details',
            name='ACCAGE',
        ),
        migrations.RemoveField(
            model_name='details',
            name='ACCID_TYPE',
        ),
        migrations.RemoveField(
            model_name='details',
            name='ACCSEX',
        ),
        migrations.RemoveField(
            model_name='details',
            name='ACCTYPE',
        ),
        migrations.RemoveField(
            model_name='details',
            name='BLACK_SPOT',
        ),
        migrations.RemoveField(
            model_name='details',
            name='BLACK_SPOT_NO',
        ),
        migrations.RemoveField(
            model_name='details',
            name='BRIEF_FACTS',
        ),
        migrations.RemoveField(
            model_name='details',
            name='BUS_NO',
        ),
        migrations.RemoveField(
            model_name='details',
            name='CATEGORY',
        ),
        migrations.RemoveField(
            model_name='details',
            name='CN_DT',
        ),
        migrations.RemoveField(
            model_name='details',
            name='CONFIRM',
        ),
        migrations.RemoveField(
            model_name='details',
            name='CONVERT',
        ),
        migrations.RemoveField(
            model_name='details',
            name='CONVERT_DATE',
        ),
        migrations.RemoveField(
            model_name='details',
            name='CONVERT_FN',
        ),
        migrations.RemoveField(
            model_name='details',
            name='DAY_NIGHT',
        ),
        migrations.RemoveField(
            model_name='details',
            name='DUPL',
        ),
        migrations.RemoveField(
            model_name='details',
            name='FLYOVER_UNDERP',
        ),
        migrations.RemoveField(
            model_name='details',
            name='FN',
        ),
        migrations.RemoveField(
            model_name='details',
            name='FOR_BLK',
        ),
        migrations.RemoveField(
            model_name='details',
            name='F_STATUS',
        ),
        migrations.RemoveField(
            model_name='details',
            name='HIT_AND_RUN_UPDATE1',
        ),
        migrations.RemoveField(
            model_name='details',
            name='INJBOY',
        ),
        migrations.RemoveField(
            model_name='details',
            name='INJFEMALE',
        ),
        migrations.RemoveField(
            model_name='details',
            name='INJGIRL',
        ),
        migrations.RemoveField(
            model_name='details',
            name='INJMALE',
        ),
        migrations.RemoveField(
            model_name='details',
            name='INJURED',
        ),
        migrations.RemoveField(
            model_name='details',
            name='Intersection',
        ),
        migrations.RemoveField(
            model_name='details',
            name='KILBOY',
        ),
        migrations.RemoveField(
            model_name='details',
            name='KILFEMALE',
        ),
        migrations.RemoveField(
            model_name='details',
            name='KILGIRL',
        ),
        migrations.RemoveField(
            model_name='details',
            name='KILLED',
        ),
        migrations.RemoveField(
            model_name='details',
            name='KILMALE',
        ),
        migrations.RemoveField(
            model_name='details',
            name='MONTH',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PEDESTRIAN',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PENDING',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PILLION_HELMET',
        ),
        migrations.RemoveField(
            model_name='details',
            name='REMARK',
        ),
        migrations.RemoveField(
            model_name='details',
            name='RIDER_HELMET',
        ),
        migrations.RemoveField(
            model_name='details',
            name='SAREA_TYPE',
        ),
        migrations.RemoveField(
            model_name='details',
            name='SCANNED',
        ),
        migrations.RemoveField(
            model_name='details',
            name='SELF_TYPE',
        ),
        migrations.RemoveField(
            model_name='details',
            name='STATE',
        ),
        migrations.RemoveField(
            model_name='details',
            name='STATUS',
        ),
        migrations.RemoveField(
            model_name='details',
            name='TIME_SLOT',
        ),
        migrations.RemoveField(
            model_name='details',
            name='VICTIM',
        ),
        migrations.RemoveField(
            model_name='details',
            name='VICTIM_PERSON_STATUS',
        ),
        migrations.RemoveField(
            model_name='details',
            name='VICTIM_PERSON_STATUS1',
        ),
        migrations.RemoveField(
            model_name='details',
            name='YEAR',
        ),
        migrations.RemoveField(
            model_name='details',
            name='case_status',
        ),
        migrations.RemoveField(
            model_name='details',
            name='convert_case',
        ),
        migrations.RemoveField(
            model_name='details',
            name='dri_add1',
        ),
        migrations.RemoveField(
            model_name='details',
            name='dri_lic_status',
        ),
        migrations.RemoveField(
            model_name='offender',
            name='dri_lic_status',
        ),
        migrations.AddField(
            model_name='details',
            name='AREA_TYPE2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fir.area_type2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='DRUNK_FAULT',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='details',
            name='FLYOVER_UNDERPASS',
            field=models.CharField(blank=True, choices=[('Ascending Flyover', 'Ascending Flyover'), ('Descending Flyover', 'Descending Flyover'), ('Ascending Flyover Loop', 'Ascending Flyover Loop'), ('Descending Flyover Loop', 'Desscending Flyover Loop')], max_length=30),
        ),
        migrations.AddField(
            model_name='details',
            name='OTHER_CAUSE',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='details',
            name='REMARKS',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='offender',
            name='ACCID_ID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fir.details'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offender',
            name='dri_relation',
            field=models.CharField(blank=True, choices=[('S/O', 'S/O'), ('D/O', 'D/O'), ('W/O', 'W/O')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='victim_vehicle',
            name='ACCID_ID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fir.details'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='details',
            name='AREA_TYPE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.area_type'),
        ),
        migrations.AlterField(
            model_name='details',
            name='AREA_TYPE_OTHER',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='details',
            name='JUNCTION_CONTROL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.junction_control'),
        ),
        migrations.AlterField(
            model_name='details',
            name='MINORROADNAME',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='details',
            name='OVER_SPEED_FAULT',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='REMEDIES',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.remedies'),
        ),
        migrations.AlterField(
            model_name='details',
            name='ROAD_CHARACTER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.road_character'),
        ),
        migrations.AlterField(
            model_name='details',
            name='ROAD_CHARACTER_REMARKS',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='details',
            name='ROAD_CONDITION',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.road_condition'),
        ),
        migrations.AlterField(
            model_name='details',
            name='ROAD_CONDITION_REMARKS',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='details',
            name='ROAD_LEVEL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.road_level'),
        ),
        migrations.AlterField(
            model_name='details',
            name='ROAD_TYPE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.road_type'),
        ),
        migrations.AlterField(
            model_name='details',
            name='ROAD_TYPE1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.road_type1'),
        ),
        migrations.AlterField(
            model_name='details',
            name='SEPERATION',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.seperation'),
        ),
        migrations.AlterField(
            model_name='details',
            name='SURFACE_CONDITION',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.surface_condition'),
        ),
        migrations.AlterField(
            model_name='details',
            name='SURFACE_CONDITION_REMARKS',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='details',
            name='SURFACE_TYPE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.surface_type'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='DRI_DRUNK',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=50),
        ),
        migrations.AlterField(
            model_name='offender',
            name='SUBVEHICLE_TYPE1',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='offender',
            name='VEHICLE_LOADED_CONDITION1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.vehicle_loaded_condition'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='dri_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='victim_vehicle',
            name='VEHICLE_LOADED_CONDITION2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.vehicle_loaded_condition'),
        ),
        migrations.DeleteModel(
            name='victim',
        ),
        migrations.AddField(
            model_name='victim_person',
            name='ACCID_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.details'),
        ),
        migrations.AddField(
            model_name='victim_person',
            name='PER_STAT_TYPE2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.victim_person_status1'),
        ),
        migrations.AddField(
            model_name='victim_person',
            name='VIC_EDU_QUAL',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.edu_qual'),
        ),
        migrations.AddField(
            model_name='victim_person',
            name='VIC_WORK_STATUS',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.work_status'),
        ),
    ]
