# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0070_auto_20170704_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='ACC_ID',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Accident ID'),
        ),
        migrations.AlterField(
            model_name='details',
            name='DATE_OCC',
            field=models.DateField(verbose_name='Acc Date'),
        ),
        migrations.AlterField(
            model_name='details',
            name='FIR_DATE',
            field=models.DateField(verbose_name='FIR Date'),
        ),
    ]
