# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0072_auto_20170704_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='CAUSE',
            field=models.CharField(choices=[('KNOWN', 'Known'), ('UNKNOWN', 'Unknown')], max_length=15, verbose_name='Cause'),
        ),
        migrations.AlterField(
            model_name='details',
            name='DRIVER_FAULT',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.driver_fault', verbose_name='Driver Fault'),
        ),
        migrations.AlterField(
            model_name='details',
            name='DRUNK_FAULT',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Drunk'),
        ),
        migrations.AlterField(
            model_name='details',
            name='LATITUDE',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='details',
            name='LONGITUDE',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='details',
            name='OTHER_CAUSE',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='details',
            name='OTHER_DRIVER_FAULT',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Other Dri Fault'),
        ),
        migrations.AlterField(
            model_name='details',
            name='OTHER_REMARK',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Other Remarks'),
        ),
        migrations.AlterField(
            model_name='details',
            name='OTHER_ROAD_ENGG_FAULT',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Other Road Engg'),
        ),
        migrations.AlterField(
            model_name='details',
            name='OTHER_ROAD_ENV_FAULT',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Other Road Env'),
        ),
        migrations.AlterField(
            model_name='details',
            name='OTHER_VEC_MEH_FAULT',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Other Vehicle Mech'),
        ),
        migrations.AlterField(
            model_name='details',
            name='OTHER_VICTIM_FAULT',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Other Victim'),
        ),
        migrations.AlterField(
            model_name='details',
            name='OTHER_WEATHER_COND_FAULT',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Other Weather Cond'),
        ),
        migrations.AlterField(
            model_name='details',
            name='OVER_SPEED_FAULT',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], default='', max_length=15, verbose_name='Over Speed'),
        ),
        migrations.AlterField(
            model_name='details',
            name='REMARKS',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='details',
            name='REMEDIES',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.remedies', verbose_name='Remedies'),
        ),
        migrations.AlterField(
            model_name='details',
            name='ROAD_CHARACTER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.road_character', verbose_name='Road Character'),
        ),
        migrations.AlterField(
            model_name='details',
            name='ROAD_CHARACTER_REMARKS',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Road Char Remarks'),
        ),
        migrations.AlterField(
            model_name='details',
            name='ROAD_CONDITION',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.road_condition', verbose_name='Road Condition'),
        ),
        migrations.AlterField(
            model_name='details',
            name='ROAD_CONDITION_REMARKS',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Road Cond Remarks'),
        ),
        migrations.AlterField(
            model_name='details',
            name='ROAD_ENGG_FAULT',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.road_engg_fault', verbose_name='Road Engg'),
        ),
        migrations.AlterField(
            model_name='details',
            name='ROAD_ENV_FAULT',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.road_env_fault', verbose_name='Road Environment'),
        ),
        migrations.AlterField(
            model_name='details',
            name='ROAD_TYPE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.road_type', verbose_name='Road Type'),
        ),
        migrations.AlterField(
            model_name='details',
            name='ROAD_TYPE1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.road_type1', verbose_name='Road Type 1'),
        ),
        migrations.AlterField(
            model_name='details',
            name='SEPERATION',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.seperation', verbose_name='Separation'),
        ),
        migrations.AlterField(
            model_name='details',
            name='SURFACE_CONDITION',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.surface_condition', verbose_name='Surface Condition'),
        ),
        migrations.AlterField(
            model_name='details',
            name='SURFACE_CONDITION_REMARKS',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Surface Cond Remarks'),
        ),
        migrations.AlterField(
            model_name='details',
            name='SURFACE_TYPE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.surface_type', verbose_name='Surface Type'),
        ),
        migrations.AlterField(
            model_name='details',
            name='VEH_MECH_FAULT',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.veh_mech_fault', verbose_name='Vehicle Mechanical'),
        ),
        migrations.AlterField(
            model_name='details',
            name='VICTIM_FAULT',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.victim_fault', verbose_name='Victim'),
        ),
        migrations.AlterField(
            model_name='details',
            name='WEATHER_COND',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.weather_cond', verbose_name='Weather Cond'),
        ),
    ]
