# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 09:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0075_auto_20170704_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collision',
            name='COL_TYPE',
            field=models.CharField(max_length=15, verbose_name='Collision Type'),
        ),
        migrations.AlterField(
            model_name='collision',
            name='VIC_TYPE',
            field=models.CharField(max_length=15, verbose_name='Victim Type'),
        ),
        migrations.AlterField(
            model_name='details',
            name='OTHER_CAUSE',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Other Causes'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='DRI_DRUNK',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=50, verbose_name='Driver Drunk/Not'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='EDU_QUAL',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.edu_qual', verbose_name='Educational Qualifications'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='OTHER_EDU_QUAL',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Other Educational Qualifications'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='OTHER_WORK_STATUS',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Other Work Status'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='STUDY_PARAMETER1',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.study_parameter', verbose_name='Study Parameter'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='SUBVEHICLE_TYPE1',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Sub Vehicle Type'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='VEHICLE_LOADED_CONDITION1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.vehicle_loaded_condition', verbose_name='Vehicle loaded Condition'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='VEHTYPE1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.vehtype1', verbose_name='Vehicle Type'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='WORK_STATUS',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.work_status', verbose_name='Work Status'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='dri_add',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Add Driver Details'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='dri_age',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)], verbose_name='Driver Age'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='dri_lic_date_issu',
            field=models.DateField(null=True, verbose_name='License Issue Date'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='dri_lic_date_upto',
            field=models.DateField(null=True, verbose_name='License Upto Date'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='dri_lic_from',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Driver License From'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='dri_lic_no',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Driver License No.'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='dri_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Driver Name'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='dri_rel_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Driver Relative Name'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='dri_relation',
            field=models.CharField(blank=True, choices=[('S/O', 'S/O'), ('D/O', 'D/O'), ('W/O', 'W/O')], default='', max_length=15, verbose_name='Driver Relation'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='dri_sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=15, verbose_name='Driver Sex'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='rcno1',
            field=models.CharField(blank=True, default=0, max_length=15, verbose_name='RC No.'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='routeno1',
            field=models.CharField(blank=True, default=0, max_length=15, verbose_name='Route No.'),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='HELMET_STANDARD',
            field=models.CharField(blank=True, choices=[('STANDARD', 'Standard'), ('SUB STANDARD', 'Sub Standard'), ('NOT KNOWN', 'Not Known')], default='', max_length=15, verbose_name='Helmet Standard'),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='INJKIL',
            field=models.CharField(choices=[('INJURED', 'Injured'), ('KILLED', 'Killed')], max_length=15, verbose_name='Injured Kil'),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='OFFEND',
            field=models.CharField(blank=True, choices=[('OFFENDING', 'Offending'), ('VICTIM VEHICLE', 'Victim Vehicle')], default='', max_length=15, verbose_name='Offend'),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='PER_STAT_TYPE',
            field=models.CharField(choices=[('SCL', 'School Children'), ('PPL', 'Police Person'), ('OTH', 'Other')], max_length=15, verbose_name='Person Status Type '),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='PER_STAT_TYPE2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.victim_person_status1', verbose_name='Person Status Type 1'),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='VEH_INFO',
            field=models.CharField(blank=True, max_length=5, verbose_name='Vehicle Info'),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='VICAGE',
            field=models.CharField(choices=[('<10', '<10'), ('11-18', '11-18'), ('19-30', '19-30'), ('31-40', '31-40'), ('>40', '>40')], max_length=15, verbose_name='Victim Age'),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='VICSEX',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=15, verbose_name='Victim Sex'),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='VIC_DRI_DRUNK',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5, verbose_name='Victim Driver Drunk/Not'),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='VIC_EDU_QUAL',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.edu_qual', verbose_name='Victim Educational Qualification'),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='VIC_HELMET',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], default='', max_length=5, verbose_name='Helmet'),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='VIC_IN_VEH',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5, verbose_name='Victim in/outside Vehicle'),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='VIC_OTHER_EDU_QUAL',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Victim Other Educational Qualification'),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='VIC_OTHER_WORK_STATUS',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Victim Other Work Status'),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='VIC_SEAT_BELT',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], default='', max_length=5, verbose_name='Victim Seat Belt'),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='VIC_WORK_STATUS',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.work_status', verbose_name='Victim Work Status'),
        ),
        migrations.AlterField(
            model_name='victim_vehicle',
            name='STUDY_PARAMETER2',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.study_parameter', verbose_name='Study Parameter'),
        ),
        migrations.AlterField(
            model_name='victim_vehicle',
            name='SUBVEHICLE_TYPE2',
            field=models.CharField(blank=True, default=0, max_length=15, verbose_name='Sub Vehicle Type'),
        ),
        migrations.AlterField(
            model_name='victim_vehicle',
            name='VEHICLE_LOADED_CONDITION2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.vehicle_loaded_condition', verbose_name='Vehicle Loaded Condition'),
        ),
        migrations.AlterField(
            model_name='victim_vehicle',
            name='VEHTYPE2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.vehtype2', verbose_name='Vehicle Type'),
        ),
        migrations.AlterField(
            model_name='victim_vehicle',
            name='rgno2',
            field=models.CharField(blank=True, default=0, max_length=15, verbose_name='Reg No.'),
        ),
        migrations.AlterField(
            model_name='victim_vehicle',
            name='routeno2',
            field=models.CharField(blank=True, default=0, max_length=15, verbose_name='Route No.'),
        ),
    ]
