# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0076_auto_20170705_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='FLYOVER_UNDERPASS',
            field=models.CharField(blank=True, choices=[('Ascending Flyover', 'Ascending Flyover'), ('Descending Flyover', 'Descending Flyover'), ('Ascending Flyover Loop', 'Ascending Flyover Loop'), ('Descending Flyover Loop', 'Descending Flyover Loop')], max_length=30, verbose_name='Flyover/Underpass'),
        ),
        migrations.AlterField(
            model_name='details',
            name='TIME_KNOWN',
            field=models.BooleanField(),
        ),
    ]
