# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0077_auto_20170708_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='TIME_KNOWN',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=30, verbose_name='Time Known'),
        ),
    ]
