# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0078_auto_20170708_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='LATITUDE',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='details',
            name='LONGITUDE',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Longitude'),
        ),
    ]
