# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0080_auto_20170709_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='circle',
            field=models.CharField(blank=True, choices=[('', 'Circle'), ('PGC', 'PAHAR GANJ CIRCLE'), ('KBC', 'KAROL BAGH CIRCLE'), ('KMC', 'KAMLA MARKET CIRCLE'), ('DGC', 'DARYA GANJ CIRCLE'), ('KPC', 'KALYAN PURI CIRCLE'), ('VKC', 'VIVEK VIHAR CIRCLE'), ('MWC', 'MANDAWALI CIRCLE'), ('GNC', 'GANDHI NAGAR CIRCLE'), ('KOT', 'KOTWALI CIRCLE'), ('CLC', 'CIVIL LINES CIRCLE'), ('SBC', 'SADAR BAZAR CIRCLE'), ('SMC', 'SABZI MANDI CIRCLE'), ('PTC', 'PARLIAMENT STREET CIRCLE'), ('TRC', 'TUGHLAK ROAD CIRCLE'), ('PTH', 'PARLIAMENT HOUSE CIRCLE'), ('TMC', 'TILAK MARG CIRCLE'), ('CHP', 'CHANAKYA PURI CIRCLE'), ('BKR', 'BARA KHAMBA ROAD CIRCLE'), ('SHD', 'SHAHDARA CIRCLE'), ('SLC', 'KHAZOORI CIRCLE'), ('SPC', 'SEEMA PURI CIRCLE'), ('MTC', 'MODEL TOWN CIRCLE'), ('NRL', 'BURARI CIRCLE'), ('AVC', 'ASHOK VIHAR CIRCLE'), ('ALP', 'NARELA CIRCLE'), ('BWC', 'BAWANA CIRCLE'), ('RHN', 'ROHINI CIRCLE'), ('MGP', 'MANGOL PURI CIRCLE'), ('IGI', 'I.G. AIR PORT CIRCLE'), ('PAP', 'PALAM AIRPORT CIRCLE'), ('DRP', 'DELHI RAILWAYS CIRCLE'), ('RKP', 'R.K. PURAM CIRCLE'), ('DFC', 'DEFENCE COLONY CIRCLE'), ('DCC', 'DELHI CANTT CIRCLE'), ('VVC', 'VASANT VIHAR CIRCLE'), ('SDV', 'SUKHDEV VIHAR CIRCLE'), ('LNC', 'LAJPAT NAGAR CIRCLE'), ('HKC', 'HAUS KHAS CIRCLE'), ('SVC', 'SARITA VIHAR CIRCLE'), ('KKC', 'KALKAJI CIRCLE'), ('SGV', 'SANGAM VIHAR CIRCLE'), ('SKT', 'SAKET CIRCLE'), ('GKC', 'GREATER KAILASH CIRCLE'), ('MRC', 'MEHRAULI CIRCLE'), ('KHC', 'KAPASHERA CIRCLE'), ('DWC', 'DWARKA CIRCLE'), ('TNC', 'TILAK NAGAR CIRCLE'), ('NJC', 'NAJAF GARH CIRCLE'), ('JPC', 'JANAK PURI CIRCLE'), ('NLC', 'NANGLOI CIRCLE'), ('PNC', 'PATEL NAGAR CIRCLE'), ('MPC', 'MAYA PURI CIRCLE'), ('PBC', 'PUNJABI BAGH CIRCLE'), ('RGC', 'RAJOURI GARDEN CIRCLE')], max_length=60),
        ),
    ]
