# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 18:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0083_auto_20170709_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collision',
            name='COL_TYPE',
            field=models.CharField(max_length=15, verbose_name='Type of Collision'),
        ),
        migrations.AlterField(
            model_name='details',
            name='ACC_PHOTO',
            field=models.FileField(blank=True, default='', upload_to='documents/', verbose_name='Picture of Accident '),
        ),
        migrations.AlterField(
            model_name='details',
            name='ACC_SKETCH_PHOTO',
            field=models.FileField(blank=True, default='', upload_to='documents/', verbose_name='Sketch of Accident'),
        ),
        migrations.AlterField(
            model_name='details',
            name='AREA_TYPE2_OTHER',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.area_type2_oth', verbose_name='Other Area Type 2'),
        ),
        migrations.AlterField(
            model_name='details',
            name='AREA_TYPE_OTHER',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Other Area Type'),
        ),
        migrations.AlterField(
            model_name='details',
            name='DRIVER_FAULT',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.driver_fault', verbose_name='Fault of Driver'),
        ),
        migrations.AlterField(
            model_name='details',
            name='DRUNK_FAULT',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Case of Drunk Driving'),
        ),
        migrations.AlterField(
            model_name='details',
            name='FIR_PHOTO',
            field=models.FileField(blank=True, default='', upload_to='documents/', verbose_name='Picture of FIR '),
        ),
        migrations.AlterField(
            model_name='details',
            name='FLYOVER_UNDERPASS',
            field=models.CharField(blank=True, choices=[('Ascending', 'Ascending'), ('Descending', 'Descending')], max_length=30, verbose_name='Flyover/Underpass'),
        ),
        migrations.AlterField(
            model_name='details',
            name='GROUND_LEVEL',
            field=models.CharField(blank=True, choices=[('JUN', 'Junction'), ('ROA', 'Round About'), ('ROS', 'Road Stretch'), ('TPT', 'T Point'), ('CUT', 'Cut')], max_length=30, verbose_name='Ground Level'),
        ),
        migrations.AlterField(
            model_name='details',
            name='JUNCTION_CONTROL',
            field=models.CharField(blank=True, choices=[('BLK', 'Blinker'), ('PM', 'Police/Manual'), ('SBM', 'Signal on Blinking Mode'), ('SNW', 'Signal Not Working'), ('SW', 'Signal Working'), ('UNC', 'Signal Uncontrolled')], max_length=30, verbose_name='Junction'),
        ),
        migrations.AlterField(
            model_name='details',
            name='MINORROADNAME',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Minor Road'),
        ),
        migrations.AlterField(
            model_name='details',
            name='MVA_NAME',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fir.mva_act', verbose_name='MVA Act'),
        ),
        migrations.AlterField(
            model_name='details',
            name='OTHER_DRIVER_FAULT',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Fault of Driver-Other'),
        ),
        migrations.AlterField(
            model_name='details',
            name='OTHER_ROAD_ENGG_FAULT',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Road Engineering Fault - Other'),
        ),
        migrations.AlterField(
            model_name='details',
            name='OTHER_ROAD_ENV_FAULT',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Road Environment Fault -Other'),
        ),
        migrations.AlterField(
            model_name='details',
            name='OTHER_VEC_MEH_FAULT',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Mechanical Fault -Other'),
        ),
        migrations.AlterField(
            model_name='details',
            name='OTHER_VICTIM_FAULT',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Fault of Victim - Other'),
        ),
        migrations.AlterField(
            model_name='details',
            name='OTHER_WEATHER_COND_FAULT',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Weather Conditions - Other'),
        ),
        migrations.AlterField(
            model_name='details',
            name='OVER_SPEED_FAULT',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], default='', max_length=15, verbose_name='Case of Overspeeding'),
        ),
        migrations.AlterField(
            model_name='details',
            name='REMARKS',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='details',
            name='ROAD_CHARACTER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.road_character', verbose_name='Character of Road'),
        ),
        migrations.AlterField(
            model_name='details',
            name='ROAD_CHARACTER_REMARKS',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Road Character-Remarks'),
        ),
        migrations.AlterField(
            model_name='details',
            name='ROAD_CONDITION_REMARKS',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Road Condition- Remarks'),
        ),
        migrations.AlterField(
            model_name='details',
            name='ROAD_ENGG_FAULT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fir.road_engg_fault', verbose_name='Fault of Road Engineering'),
        ),
        migrations.AlterField(
            model_name='details',
            name='ROAD_ENV_FAULT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fir.road_env_fault', verbose_name='Fault of Road Environment'),
        ),
        migrations.AlterField(
            model_name='details',
            name='ROAD_LEVEL',
            field=models.CharField(blank=True, choices=[('FLYO', 'Flyover'), ('UNPA', 'Underpass'), ('GRL', 'Ground Level')], max_length=30, verbose_name='Road Level'),
        ),
        migrations.AlterField(
            model_name='details',
            name='SURFACE_CONDITION_REMARKS',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Surface Condition-Remarks'),
        ),
        migrations.AlterField(
            model_name='details',
            name='VEH_MECH_FAULT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fir.veh_mech_fault', verbose_name='Mechanical Fault of Vehicle'),
        ),
        migrations.AlterField(
            model_name='details',
            name='VICTIM_FAULT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fir.victim_fault', verbose_name='Fault of Victim'),
        ),
        migrations.AlterField(
            model_name='details',
            name='WEATHER_COND',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fir.weather_cond', verbose_name='Weather Conditions'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='DRI_DRUNK',
            field=models.CharField(blank=True, max_length=50, verbose_name='Driver Drunk/Not'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='OTHER_EDU_QUAL',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Educational Qualifications - Other'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='OTHER_WORK_STATUS',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Work Status - Other'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='STUDY_PARAMETER1',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.study_parameter', verbose_name='Study Parameters'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='VEHICLE_LOADED_CONDITION1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.vehicle_loaded_condition', verbose_name='Load of Vehicle'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='VEHTYPE1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.vehtype1', verbose_name='Type of Vehicle'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='dri_add',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='dri_age',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)], verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='dri_lic_no',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='License No.'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='dri_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Name of Driver'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='dri_rel_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Name of Relative'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='dri_relation',
            field=models.CharField(blank=True, choices=[('S/O', 'S/O'), ('D/O', 'D/O'), ('W/O', 'W/O')], default='', max_length=15, verbose_name='Relative of Driver'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='dri_sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=15, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='HELMET_STANDARD',
            field=models.CharField(blank=True, choices=[('STANDARD', 'Standard'), ('SUB STANDARD', 'Sub Standard'), ('NOT KNOWN', 'Not Known')], default='', max_length=15, verbose_name='Standard of Helmet'),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='INJKIL',
            field=models.CharField(choices=[('INJURED', 'Injured'), ('KILLED', 'Killed')], max_length=15, verbose_name='Injured or Killed'),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='OFFEND',
            field=models.CharField(blank=True, choices=[('OFFENDING', 'Offending'), ('VICTIM VEHICLE', 'Victim Vehicle')], default='', max_length=15, verbose_name='Offending/Victim Vehicle'),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='PER_STAT_TYPE',
            field=models.CharField(choices=[('SCL', 'School Children'), ('PPL', 'Police Person'), ('OTH', 'Other')], max_length=15, verbose_name='Type of Person'),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='PER_STAT_TYPE2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.victim_person_status1', verbose_name='Person Status'),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='VICAGE',
            field=models.CharField(choices=[('<10', '<10'), ('11-18', '11-18'), ('19-30', '19-30'), ('31-40', '31-40'), ('>40', '>40')], max_length=15, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='VICSEX',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=15, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='VIC_DRI_DRUNK',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5, verbose_name='Drunk/Not'),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='VIC_EDU_QUAL',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.edu_qual', verbose_name='Educational Qualification'),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='VIC_HELMET',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], default='', max_length=5, verbose_name='Helmet Worn'),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='VIC_IN_VEH',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5, verbose_name='Victim inside/outside Vehicle'),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='VIC_OTHER_EDU_QUAL',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Educational Qualifications - Other'),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='VIC_OTHER_WORK_STATUS',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Work Status - Other'),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='VIC_SEAT_BELT',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], default='', max_length=5, verbose_name='Seatbelt Worn'),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='VIC_WORK_STATUS',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.work_status', verbose_name='Work Status'),
        ),
        migrations.AlterField(
            model_name='victim_vehicle',
            name='STUDY_PARAMETER2',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.study_parameter', verbose_name='Study Parameters'),
        ),
        migrations.AlterField(
            model_name='victim_vehicle',
            name='VEHICLE_LOADED_CONDITION2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.vehicle_loaded_condition', verbose_name='Load of Vehicle'),
        ),
        migrations.AlterField(
            model_name='victim_vehicle',
            name='VEHTYPE2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.vehtype2', verbose_name='Type of Vehicle'),
        ),
        migrations.AlterField(
            model_name='victim_vehicle',
            name='rgno2',
            field=models.CharField(blank=True, default=0, max_length=15, verbose_name='Registration No.'),
        ),
        migrations.DeleteModel(
            name='ground_level',
        ),
        migrations.DeleteModel(
            name='junction_control',
        ),
        migrations.DeleteModel(
            name='road_level',
        ),
    ]
