# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0085_auto_20170710_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='AREA_TYPE2_OTHER',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='fir.area_type2_oth', verbose_name='Other Area Type 2'),
        ),
        migrations.AlterField(
            model_name='details',
            name='AREA_TYPE_OTHER',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Other Area Type'),
        ),
        migrations.AlterField(
            model_name='details',
            name='DRIVER_FAULT',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='fir.driver_fault', verbose_name='Fault of Driver'),
        ),
    ]
