# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0086_auto_20170710_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offender',
            name='EDU_QUAL',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='fir.edu_qual', verbose_name='Educational Qualifications'),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='VIC_EDU_QUAL',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='fir.edu_qual', verbose_name='Educational Qualifications'),
        ),
    ]
