# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0087_auto_20170710_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim_person',
            name='VIC_WORK_STATUS',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='fir.work_status', verbose_name='Work Status'),
        ),
    ]
