# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0088_auto_20170710_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='LOCATION',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fir.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='STUDY_PARAMETER1',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='fir.study_parameter', verbose_name='Study Parameters'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='WORK_STATUS',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='fir.work_status', verbose_name='Work Status'),
        ),
        migrations.AlterField(
            model_name='victim_vehicle',
            name='STUDY_PARAMETER2',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='fir.study_parameter', verbose_name='Study Parameters'),
        ),
    ]
