# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0089_auto_20170710_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='AREA_TYPE2',
        ),
        migrations.RemoveField(
            model_name='details',
            name='AREA_TYPE2_OTHER',
        ),
        migrations.AlterField(
            model_name='details',
            name='LOCATION',
            field=models.ForeignKey(blank=True, default=11, on_delete=django.db.models.deletion.CASCADE, to='fir.location', verbose_name='Location'),
        ),
    ]
