# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0090_auto_20170710_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='LOCATION',
            new_name='AREA_TYPE2',
        ),
    ]
