# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0092_auto_20170710_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='ROAD_TYPE1',
            field=models.CharField(blank=True, choices=[('ONE WAY', 'One Way'), ('TWO WAY', 'Two Way')], max_length=30, verbose_name='Road Type 1'),
        ),
    ]
