# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 10:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0093_auto_20170710_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offender',
            name='RNOV1A',
        ),
        migrations.RemoveField(
            model_name='offender',
            name='RNOV1B',
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='VICAGE',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)], verbose_name='Age'),
        ),
    ]
