# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0094_auto_20170710_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='offender',
            name='dri_lic',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='N', max_length=5, verbose_name='Driver has License?'),
            preserve_default=False,
        ),
    ]
