# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0095_offender_dri_lic'),
    ]

    operations = [
        migrations.CreateModel(
            name='causes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CAUSE', models.CharField(choices=[('KNOWN', 'Known'), ('UNKNOWN', 'Unknown')], max_length=15, verbose_name='Cause')),
                ('OTHER_DRIVER_FAULT', models.CharField(blank=True, default='', max_length=50, verbose_name='Fault of Driver-Other')),
                ('DRUNK_FAULT', models.CharField(blank=True, default='', max_length=25, verbose_name='Case of Drunk Driving')),
                ('OVER_SPEED_FAULT', models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], default='', max_length=15, verbose_name='Case of Overspeeding')),
                ('OTHER_VEC_MEH_FAULT', models.CharField(blank=True, default='', max_length=50, verbose_name='Mechanical Fault -Other')),
                ('OTHER_ROAD_ENV_FAULT', models.CharField(blank=True, default='', max_length=50, verbose_name='Road Environment Fault -Other')),
                ('OTHER_ROAD_ENGG_FAULT', models.CharField(blank=True, default='', max_length=50, verbose_name='Road Engineering Fault - Other')),
                ('OTHER_VICTIM_FAULT', models.CharField(blank=True, default='', max_length=50, verbose_name='Fault of Victim - Other')),
                ('OTHER_WEATHER_COND_FAULT', models.CharField(blank=True, default='', max_length=50, verbose_name='Weather Conditions - Other')),
                ('OTHER_CAUSE', models.CharField(blank=True, default='', max_length=1000, verbose_name='Other Causes')),
                ('REMARKS', models.CharField(blank=True, default='', max_length=200, verbose_name='Remarks')),
                ('OTHER_REMARK', models.CharField(blank=True, default='', max_length=50, verbose_name='Other Remarks')),
                ('DRIVER_FAULT', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='fir.driver_fault', verbose_name='Fault of Driver')),
                ('REMEDIES', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.remedies', verbose_name='Remedies')),
                ('ROAD_ENGG_FAULT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fir.road_engg_fault', verbose_name='Fault of Road Engineering')),
                ('ROAD_ENV_FAULT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fir.road_env_fault', verbose_name='Fault of Road Environment')),
                ('VEH_MECH_FAULT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fir.veh_mech_fault', verbose_name='Mechanical Fault of Vehicle')),
                ('VICTIM_FAULT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fir.victim_fault', verbose_name='Fault of Victim')),
                ('WEATHER_COND', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fir.weather_cond', verbose_name='Weather Conditions')),
            ],
        ),
        migrations.RemoveField(
            model_name='details',
            name='CAUSE',
        ),
        migrations.RemoveField(
            model_name='details',
            name='DRIVER_FAULT',
        ),
        migrations.RemoveField(
            model_name='details',
            name='DRUNK_FAULT',
        ),
        migrations.RemoveField(
            model_name='details',
            name='OTHER_CAUSE',
        ),
        migrations.RemoveField(
            model_name='details',
            name='OTHER_DRIVER_FAULT',
        ),
        migrations.RemoveField(
            model_name='details',
            name='OTHER_REMARK',
        ),
        migrations.RemoveField(
            model_name='details',
            name='OTHER_ROAD_ENGG_FAULT',
        ),
        migrations.RemoveField(
            model_name='details',
            name='OTHER_ROAD_ENV_FAULT',
        ),
        migrations.RemoveField(
            model_name='details',
            name='OTHER_VEC_MEH_FAULT',
        ),
        migrations.RemoveField(
            model_name='details',
            name='OTHER_VICTIM_FAULT',
        ),
        migrations.RemoveField(
            model_name='details',
            name='OTHER_WEATHER_COND_FAULT',
        ),
        migrations.RemoveField(
            model_name='details',
            name='OVER_SPEED_FAULT',
        ),
        migrations.RemoveField(
            model_name='details',
            name='REMARKS',
        ),
        migrations.RemoveField(
            model_name='details',
            name='REMEDIES',
        ),
        migrations.RemoveField(
            model_name='details',
            name='ROAD_ENGG_FAULT',
        ),
        migrations.RemoveField(
            model_name='details',
            name='ROAD_ENV_FAULT',
        ),
        migrations.RemoveField(
            model_name='details',
            name='VEH_MECH_FAULT',
        ),
        migrations.RemoveField(
            model_name='details',
            name='VICTIM_FAULT',
        ),
        migrations.RemoveField(
            model_name='details',
            name='WEATHER_COND',
        ),
    ]
