# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0096_auto_20170711_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='causes',
            name='ACCID_ID',
            field=models.ForeignKey(default='2017IE1', on_delete=django.db.models.deletion.CASCADE, to='fir.details'),
            preserve_default=False,
        ),
    ]
