# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0098_auto_20170711_0400'),
        ('fir', '0097_causes_accid_id'),
    ]

    operations = [
    ]
