# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0099_merge_20170711_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collision',
            name='COL_TYPE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.accid_type', verbose_name='Type of Collision'),
        ),
        migrations.AlterField(
            model_name='collision',
            name='VIC_TYPE',
            field=models.CharField(choices=[('SELF', 'SELF'), ('SELF/ANIMAL', 'SELF/ANIMAL'), ('PASSENGER', 'PASSENGER'), ('PEDESTRIAN', 'PEDESTRIAN'), ('VEHICLES', 'VEHICLES'), ('VEHICLES/PED', 'VEHICLES/PED')], max_length=15, verbose_name='Victim Type'),
        ),
    ]
