# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 11:11
from __future__ import unicode_literals

import django.contrib.gis.geos.point
from django.db import migrations, models
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0100_auto_20170712_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='map_loc',
            field=location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(77.1025, 28.7041), srid=4326),
        ),
        migrations.AlterField(
            model_name='offender',
            name='SUBVEHICLE_TYPE1',
            field=models.CharField(blank=True, choices=[('Scooter', 'Scooter'), ('Scooty', 'Scooty'), ('Motor bike', 'Motor bike'), ('N/A', 'N/A')], default='N/A', max_length=15, verbose_name='Sub Vehicle Type'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='dri_lic',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=5, verbose_name='Driver has License?'),
        ),
        migrations.AlterField(
            model_name='victim_vehicle',
            name='SUBVEHICLE_TYPE2',
            field=models.CharField(blank=True, choices=[('Scooter', 'Scooter'), ('Scooty', 'Scooty'), ('Motor bike', 'Motor bike'), ('N/A', 'N/A')], default='N/A', max_length=15, verbose_name='Sub Vehicle Type'),
        ),
    ]
