# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0101_auto_20170712_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='LATITUDE',
        ),
        migrations.RemoveField(
            model_name='details',
            name='LONGITUDE',
        ),
        migrations.AddField(
            model_name='details',
            name='APZ',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Accident Prone Zone'),
        ),
        migrations.AddField(
            model_name='details',
            name='APZ_TYPE',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='APZ Type'),
        ),
    ]
