# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0102_auto_20170713_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='ILLUMINATION',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=50, verbose_name='Illumination'),
        ),
        migrations.AddField(
            model_name='details',
            name='ROAD_MARKING',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('FADED', 'Faded')], max_length=50, verbose_name='Road Markings'),
        ),
        migrations.AddField(
            model_name='details',
            name='ROAD_SIGN',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('FADED', 'Faded')], max_length=50, verbose_name='Road Signs'),
        ),
        migrations.AddField(
            model_name='details',
            name='YES_ILLUMINATION',
            field=models.CharField(blank=True, choices=[('WORKING', 'Working'), ('NOT WORKING', 'Not Working')], max_length=50, verbose_name='Illumination Working'),
        ),
    ]
