# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 10:49
from __future__ import unicode_literals

import django.contrib.gis.geos.point
from django.db import migrations, models
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0104_auto_20170718_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='map_loc',
            field=location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(77.1025, 28.7041), srid=4326, verbose_name='Lat/Long'),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='VIC_DRI_DRUNK',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO'), ('UNKNOWN', 'UNKNOWN')], max_length=15, verbose_name='Drunk/Not'),
        ),
    ]
