# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0105_auto_20170718_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='FN',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='details',
            name='MONTH',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='OFFEND',
            field=models.CharField(blank=True, choices=[('OFFENDING VEHICLE', 'Offending Vehicle'), ('VICTIM VEHICLE', 'Victim Vehicle')], default='', max_length=15, verbose_name='Offending/Victim Vehicle'),
        ),
    ]
