# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0106_auto_20170719_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='FN',
        ),
        migrations.RemoveField(
            model_name='details',
            name='MONTH',
        ),
        migrations.RemoveField(
            model_name='offender',
            name='STUDY_PARAMETER1',
        ),
        migrations.RemoveField(
            model_name='victim_vehicle',
            name='STUDY_PARAMETER2',
        ),
        migrations.AddField(
            model_name='details',
            name='MOB_NUM',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='Mobile No.'),
        ),
        migrations.AddField(
            model_name='details',
            name='NAME_IO',
            field=models.CharField(blank=True, default='', max_length=140, verbose_name='Name Of IO'),
        ),
        migrations.AddField(
            model_name='details',
            name='PIS_NUM',
            field=models.CharField(blank=True, default='', max_length=140, verbose_name='PIS No.'),
        ),
        migrations.AddField(
            model_name='offender',
            name='dri_lic_perm',
            field=models.CharField(blank=True, max_length=25, verbose_name='Permanent License Type'),
        ),
        migrations.AddField(
            model_name='offender',
            name='dri_lic_yes',
            field=models.CharField(blank=True, choices=[('LEARNER', 'Learner'), ('PERMANENT', 'Permanent')], max_length=25, verbose_name='Type of License?'),
        ),
        migrations.AlterField(
            model_name='causes',
            name='OTHER_REMARK',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Special Observations'),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='OFFEND',
            field=models.CharField(blank=True, choices=[('OFFENDING', 'Offending'), ('VICTIM VEHICLE', 'Victim Vehicle')], default='', max_length=15, verbose_name='Offending/Victim Vehicle'),
        ),
        migrations.AlterField(
            model_name='victim_person',
            name='VIC_IN_VEH',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO'), ('UNKNOWN', 'UNKNOWN')], max_length=15, verbose_name='Victim inside/outside Vehicle'),
        ),
    ]
