# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0107_auto_20170725_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='ACC_PHOTO1',
            field=models.FileField(blank=True, default='', null=True, upload_to='documents/', verbose_name='Picture of Accident '),
        ),
        migrations.AddField(
            model_name='details',
            name='ACC_PHOTO2',
            field=models.FileField(blank=True, default='', null=True, upload_to='documents/', verbose_name='Picture of Accident '),
        ),
        migrations.AddField(
            model_name='details',
            name='ACC_PHOTO3',
            field=models.FileField(blank=True, default='', null=True, upload_to='documents/', verbose_name='Picture of Accident '),
        ),
        migrations.AddField(
            model_name='details',
            name='ACC_PHOTO4',
            field=models.FileField(blank=True, default='', null=True, upload_to='documents/', verbose_name='Picture of Accident '),
        ),
        migrations.AddField(
            model_name='details',
            name='ACC_PHOTO5',
            field=models.FileField(blank=True, default='', null=True, upload_to='documents/', verbose_name='Picture of Accident '),
        ),
    ]
