# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 02:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0110_auto_20170726_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='causes',
            name='OTHER_REMEDIES',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Remedies - Other'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='dri_age',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)], verbose_name='Age'),
        ),
    ]
