# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 02:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0111_auto_20170726_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offender',
            name='dri_age',
        ),
    ]
