# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 02:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0112_remove_offender_dri_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='offender',
            name='dri_age',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)], verbose_name='Age'),
        ),
    ]
